# Oretoku-theme-jekyll
# ver. 0.0.1
# 2017 Ikubaku <hide4d51@gmail.com>
# Published under the MIT license

# Setting for GitHub Pages
exclude: [readme.md, README.md]

# Time Zone
timezone: Asia/Tokyo

# Encoding
#encoding: utf-8

# Plugins
plugins:
  - jekyll-paginate

# Paginate configuration
paginate: 5
paginate_path: "/blog/page:num/"

# Permalink configuration
permalink: /blog/:year/:month/:day/:title/

# Theme settings
# Your page's title
name: "My Page"
# IP infomation(such as copy-right notice)
ip_info: "2017 C Ikubaku - Published under the MIT License"
# Texts shown on the post navigator when there is no next/previous post available
previous_noentry: "投稿がありません"
next_noentry: "投稿がありません"

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
