# Oretoku-theme-jekyll
# ver. 0.0.1
# 2017 Ikubaku <hide4d51@gmail.com>
# Published under the MIT license

# Setting for GitHub Pages
exclude: [readme.md, README.md]

# Time Zone
timezone: Asia/Tokyo

# Encoding
#encoding: uft-8

# Plugins
plugins:
  - jekyll-paginate

# Paginate configuration
paginate: 5
paginate_path: "/blog/page:num/"

# Theme specific settings
# Your page's title
name: "My Page"
# IP infomation(such as copy-right notice)
ip_info: "2017 C Ikubaku - Published under the MIT License"

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
